### PR TITLE
Update manyverse_0.2209.2-beta_amd64.deb to 0.2210.3-beta

### PR DESCRIPTION
**Pull request by staltz**
Doing this manually because the bot didn't show up on October 3rd.

### CODE REVIEW

**Comment by staltz** [comment]
@ebassi @wjt @nedrichards Hi! Could you help me figure out what's wrong with the build? The bot didn't trigger this PR this month, when it typically should, so I made a PR manually. The build is failing because

```
ERROR   src.manifest: Failed to check file manyverse-desktop/manyverse_0.2210.3-beta_amd64.deb 
with HTMLChecker: Pattern 'manyverse_(.*)_amd64.deb' didn't match anything
```

which doesn't make sense to me, neither the pattern nor the filename have changed.

**Comment by wjt** [comment]
Rather than debugging this, I suggest using the JSON checker to look at github releases, as desrcibed in https://github.com/flathub/flatpak-external-data-checker/#json-checker

**Comment by nicopace** [comment]
The URL that should be checked apparently is https://api.github.com/repos/staltz/manyverse/releases , and the JSONChecker content seems to have to be something like this:
```JSON
"x-checker-data": {
    "type": "json",
    "url": "https://api.github.com/repos/staltz/manyverse/releases",
    "tag-query": ".tag_name",
    "version-query": "$tag | sub(\"^jq-\"; \"\")",
    "timestamp-query": ".published_at"
}
```

I hope this helps.

**Comment by staltz** [comment]
Thanks @nicopace . I triple checked it and it seems it's already correct.

Help @wjt ?

**Comment by wjt** [comment]
My advice remains the same: use the JSON checker.

**Comment by wjt** [comment]
The reason the check you have written doesn't work is that the HTML content at https://github.com/staltz/manyverse/releases does not match the regular expression `manyverse_(.*)_amd64.deb`.

**Comment by staltz** [comment]
Thanks, now I understood what you meant, *replace* the HTML checker with JSON checker.

**Comment by staltz** [comment]
I installed it and tested it.

**Pull request merged**
